repos:
    -   repo: https://github.com/ambv/black
        rev: 21.7b0
        hooks:
        - id: black
          entry: bash -c 'black "$@"; git add -u' --
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.11.5
        hooks:
        -   id: isort
            entry: bash -c 'isort "$@"; git add -u' --
    -   repo: https://github.com/pycqa/flake8
        rev: 3.9.2
        hooks:
        - id: flake8
          additional_dependencies: [ radon ]
          entry: bash -c 'flake8 --radon-no-assert --radon-max-cc 7' --