name: Tests Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest 
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    
    - name: Run flake8 (suo)
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest tests/
